# -*- coding: utf-8 -*-
import sqlite3
# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLineEdit, QMessageBox

class Ui_LoginWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 500)
        MainWindow.setStyleSheet("background-color: rgb(75, 53, 38);\n"
"color: rgb(255, 234, 197);")
        MainWindow.setWindowTitle("BeanStock")
        MainWindow.setWindowIcon(QtGui.QIcon('img/coffee-cup.png'))
        MainWindow.setFixedSize(800, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.login_widget = QtWidgets.QWidget(self.centralwidget)
        self.login_widget.setGeometry(QtCore.QRect(360, 25, 410, 450))
        self.login_widget.setStyleSheet("background-color: rgb(255, 234, 197);\n"
"border-radius: 50px;\n"
"color: rgb(75, 53, 38);")
        self.login_widget.setObjectName("login_widget")
        self.username = QtWidgets.QLineEdit(self.login_widget)
        self.username.setGeometry(QtCore.QRect(30, 190, 340, 31))
        self.username.setStyleSheet("background-color: transparent;\n"
"border-bottom:  2px solid rgb(75, 53, 38);\n"
"font: 11pt \"Comic Sans MS\";")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.login_widget)
        self.password.setGeometry(QtCore.QRect(30, 270, 340, 31))
        self.password.setEchoMode(QLineEdit.Password)
        self.password.setStyleSheet("background-color: transparent;\n"
"border-bottom:  2px solid rgb(75, 53, 38);\n"
"font: 11pt \"Comic Sans MS\";")
        self.password.setObjectName("password")
        self.show_password = QtWidgets.QLineEdit(self.login_widget)
        self.show_password.setGeometry(QtCore.QRect(30, 270, 340, 31))
        self.show_password.setStyleSheet("background-color: transparent;\n"
"border-bottom:  2px solid rgb(75, 53, 38);\n"
"font: 11pt \"Comic Sans MS\";")
        self.show_password.setObjectName("show_password")
        self.show_password.hide()
        self.login_label = QtWidgets.QLabel(self.login_widget)
        self.login_label.setGeometry(QtCore.QRect(155, 80, 141, 81))
        self.login_label.setStyleSheet("font: 25pt \"Comic Sans MS\";\n"
"")
        self.login_label.setObjectName("login_label")
        self.login_icon = QtWidgets.QLabel(self.login_widget)
        self.login_icon.setGeometry(QtCore.QRect(165, 20, 81, 71))
        self.login_icon.setText("")
        self.login_icon.setPixmap(QtGui.QPixmap("img/login-avatar.png"))
        self.login_icon.setScaledContents(True)
        self.login_icon.setObjectName("login_icon")
        self.username_label = QtWidgets.QLabel(self.login_widget)
        self.username_label.setGeometry(QtCore.QRect(30, 150, 91, 41))
        self.username_label.setStyleSheet("font: 11pt \"Comic Sans MS\";")
        self.username_label.setObjectName("username_label")
        self.password_label = QtWidgets.QLabel(self.login_widget)
        self.password_label.setGeometry(QtCore.QRect(30, 230, 91, 41))
        self.password_label.setStyleSheet("font: 11pt \"Comic Sans MS\";")
        self.password_label.setObjectName("password_label")
        self.login_btn = QtWidgets.QPushButton(self.login_widget)
        self.login_btn.setGeometry(QtCore.QRect(155, 350, 101, 51))
        self.login_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_btn.setStyleSheet("background-color: rgb(75, 53, 38);\n"
"font: 14pt \"Comic Sans MS\";\n"
"color: rgb(255, 234, 197);\n"
"border-radius: 10px;")
        self.login_btn.setObjectName("login_btn")
        self.show_password_btn = QtWidgets.QPushButton(self.login_widget)
        self.show_password_btn.setGeometry(QtCore.QRect(325, 270, 51, 24))
        self.show_password_btn.setObjectName("show_password_btn")
        show_icon = QtGui.QIcon("img/eye.png")
        self.show_password_btn.setIcon(show_icon)
        self.show_password_btn.setIconSize(QtCore.QSize(30, 30))
        self.show_password_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.hide_password_btn = QtWidgets.QPushButton(self.login_widget)
        self.hide_password_btn.setGeometry(QtCore.QRect(325, 270, 51, 24))
        self.hide_password_btn.setObjectName("hide_password_btn")
        hide_icon = QtGui.QIcon("img/hidden.png")
        self.hide_password_btn.setIcon(hide_icon)
        self.hide_password_btn.setIconSize(QtCore.QSize(30, 30))
        self.hide_password_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.hide_password_btn.hide()
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(70, 240, 301, 111))
        self.title.setStyleSheet("font: 25pt \"Comic Sans MS\";"
                                 "background-color: transparent;")
        self.title.setObjectName("title")
        self.icon = QtWidgets.QLabel(self.centralwidget)
        self.icon.setGeometry(QtCore.QRect(70, 100, 201, 171))
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap("img/coffee-cup.png"))
        self.icon.setScaledContents(True)
        self.icon.setObjectName("icon")
        self.tagline = QtWidgets.QLabel(self.centralwidget)
        self.tagline.setGeometry(QtCore.QRect(50, 330, 241, 80))
        self.tagline.setStyleSheet("font: 9pt \"Comic Sans MS\";\n"
"background-color: transparent;")
        self.tagline.setObjectName("tagline")


        self.hide_password_btn.clicked.connect(self.hide_password_func)
        self.show_password_btn.clicked.connect(self.show_password_func)
        self.password.textChanged.connect(self.sync_fields)
        self.show_password.textChanged.connect(self.sync_fields)
        self.login_btn.clicked.connect(self.login)

        self.login_widget.raise_()
        self.title.raise_()
        self.icon.raise_()
        self.tagline.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.login_label.setText(_translate("MainWindow", "Login"))
        self.username_label.setText(_translate("MainWindow", "Username:"))
        self.password_label.setText(_translate("MainWindow", "Password:"))
        self.login_btn.setText(_translate("MainWindow", "Login"))
        self.title.setText(_translate("MainWindow", "BeanStock"))
        self.tagline.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Keep Your Coffee Flowing,</p><p align=\"center\">Your Inventory in Check</p></body></html>"))


    def sync_fields(self):
        if self.password.isVisible():
            self.show_password.setText(self.password.text())
        else:
            self.password.setText(self.show_password.text())

    def show_password_func(self):
        self.password.hide()
        self.show_password.show()
        self.show_password_btn.hide()
        self.hide_password_btn.show()

    def hide_password_func(self):
        self.show_password.hide()
        self.password.show()
        self.hide_password_btn.hide()
        self.show_password_btn.show()

    def login(self):
        try:
            username = self.username.text()
            password = self.password.text() if self.password.isVisible() else self.show_password.text()

            if not username or not password:
                self.show_message("Input Error", "Username and password cannot be empty.", QMessageBox.Warning)
                return

            connection = sqlite3.connect("coffee_shop.db")
            cursor = connection.cursor()

            cursor.execute("SELECT * FROM users WHERE username = ? AND password = ?", (username, password))
            result = cursor.fetchone()

            if result:
                self.open_main_window()
            else:
                self.show_message("Login Failed", "Incorrect username or password.", QMessageBox.Warning)

        except sqlite3.Error as e:
            print(f"Database error: {e}")
            self.show_message("Database Error", f"An error occurred while accessing the database: {e}",
                              QMessageBox.Critical)
        except Exception as e:
            print(f"Unexpected error: {e}")
            self.show_message("Error", "An unexpected error occurred while processing the login.", QMessageBox.Critical)
        finally:
            if 'connection' in locals():
                connection.close()

    def show_message(self, title, message, icon):
        QMessageBox(icon, title, message).exec_()

    def open_main_window(self):
        from main import Ui_MainWindow

        self.main_window = QtWidgets.QMainWindow()

        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.main_window)

        self.main_window.show()

        self.login_window.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)

    login_window = QtWidgets.QMainWindow()
    login_ui = Ui_LoginWindow()
    login_ui.setupUi(login_window)
    login_window.setWindowTitle("BeanStock")
    login_ui.login_window = login_window
    login_window.show()
    sys.exit(app.exec_())

